# -*- coding: utf-8 -*-
"""task2_data_processing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15xzMKhgTdrJrdepcH9LVHHsk5kkJjOGn
"""

from google.colab import files
files.upload()

import pandas as pd
import os

# Use your uploaded file name
file_path = "trends_20260409.json"

# Load JSON file
df = pd.read_json(file_path)
print(f"Loaded {len(df)} stories from {file_path}")

# Removing duplicate stories
df = df.drop_duplicates(subset="post_id")
print(f"After removing duplicates: {len(df)}")

# Removing rows with missing important values
df = df.dropna(subset=["post_id", "title", "score"])
print(f"After removing nulls: {len(df)}")

# Convert score and comments to integers
df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].astype(int)

# Removing low score stories
df = df[df["score"] >= 5]
print(f"After removing low scores: {len(df)}")

# Cleaning title text
df["title"] = df["title"].str.strip()

# Create data folder
os.makedirs("data", exist_ok=True)

# Save cleaned CSV
output_path = "data/trends_clean.csv"
df.to_csv(output_path, index=False)

print(f"\nSaved {len(df)} rows to {output_path}")

# Show category summary
print("\nStories per category:")
print(df["category"].value_counts())

from google.colab import files
files.download("data/trends_clean.csv")
