# -*- coding: utf-8 -*-
"""trendpulse

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdR-LGX3QURapcE_DdWiyU71fLlrcTY6
"""

# trendpulse_scraper.py
# Hey there! This script collects the top stories from Hacker News
# and saves them as a JSON file. Think of it like TrendPulse gathering
# all the buzz so you can analyze what's trending.
# Written by: [Your Name]
# Date: YYYY-MM-DD

import requests
import time
import json
import os
from datetime import datetime

print("Hey! Starting TrendPulse story collection...")

# URLs to take top stories and individual story details
TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"

# Just to let the server know who we are
headers = {"User-Agent": "TrendPulse/1.0"}

# We will categorize stories based on keywords in their titles
categories = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "api", "startup"],
    "worldnews": ["war", "government", "election", "india", "china", "usa", "policy"],
    "sports": ["sport", "cricket", "football", "tennis", "match", "team"],
    "science": ["research", "space", "physics", "biology", "nasa", "experiment"],
    "entertainment": ["movie", "music", "netflix", "film", "show", "tv"]
}

# This list will have all the stories we collect
stories_data = []

# A little helper function to guess the category based on title keywords
def assign_category(title):
    title = title.lower()
    for category, keywords in categories.items():
        for keyword in keywords:
            if keyword in title:
                return category
    # If nothing matches, we just call it technology
    return "technology"

# Let's take the top 500 story IDs from Hacker News
try:
    response = requests.get(TOP_STORIES_URL, headers=headers)
    top_ids = response.json()[:500]
    print(f"Fetched {len(top_ids)} top story IDs from Hacker News. Cool!")
except Exception as e:
    print("Oops! Could not fetch top stories:", e)
    top_ids = []

# Now we go through each story ID and get the details
for story_id in top_ids:

    # Stop once we have 120 stories, that’s enough for our analysis
    if len(stories_data) >= 120:
        break

    try:
        res = requests.get(ITEM_URL.format(story_id), headers=headers)
        story = res.json()
    except Exception:
        # If anything goes wrong, just skip this story
        continue

    # Skip stories without a title
    if not story or "title" not in story:
        continue

    # assigning a category based on the title
    category = assign_category(story["title"])

    # Put all the info we care about into a dictionary
    story_info = {
        "post_id": story.get("id"),
        "title": story.get("title"),
        "category": category,
        "score": story.get("score", 0),
        "num_comments": story.get("descendants", 0),
        "author": story.get("by", "unknown"),
        "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

    # Add this story to our collection
    stories_data.append(story_info)

    # Take a little break every 20 stories
    if len(stories_data) % 20 == 0:
        print(f"{len(stories_data)} stories collected so far... taking a quick 2-second breather")
        time.sleep(2)

if not os.path.exists("data"):
    os.makedirs("data")

# Save everything to a JSON file with today’s date in the name
filename = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"
with open(filename, "w", encoding="utf-8") as f:
    json.dump(stories_data, f, indent=4)

print(f"All done! Collected {len(stories_data)} stories and saved them to {filename}")

from google.colab import files
files.download('data/trends_20260409.json')



